# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa2e617489eff7ae101a34486a106d60fcdcfb1780c852a9ea76e141d7eaf2aac2118c81636afc2e991a27b8fd078366c9a9a165c9d55cd649ca3d007415bf9

test:
  secret_key_base: aef83e16d32381a5b69327dc01c52cb22dd1d067bb72f548a95760b60bfbff54e1a134888a2660ce0ee27d8751eff5a00530e9a67d2ba8a79e77476314751d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
